### ISSUE TITLE
how to make fetch  execute a pre-defined trajectory in gazebo.

### ISSUE THREAD

**Issue by wangjiwang** [fetchrobotics/fetch_gazebo#103]
I don't have any hardware now, and I download this package. how to make fetch  execute a pre-defined trajectory in gazebo? can anybody help me and tell me more details?

**Comment by erelson** [comment]
Hi @wangjiwang, the intro documentation should get you started: http://docs.fetchrobotics.com/gazebo.html

The code behind these examples is in the demos folder of this repo: https://github.com/fetchrobotics/fetch_gazebo/tree/gazebo9/fetch_gazebo_demo/scripts

**Comment by wangjiwang** [comment]
Thanks for your reply. And I try to use
arm_with_torso_controller/follow_joint_trajectory controller to execute a
pre-defined trajectory. It did not work. The API did not give detail
information. Can you give a example? The attachment is my code.


Eric Relson <notifications@github.com> 于2020年7月2日周四 下午11:56写道：

**Comment by wangjiwang** [comment]
> Hi @wangjiwang, the intro documentation should get you started: http://docs.fetchrobotics.com/gazebo.html
> 
> The code behind these examples is in the demos folder of this repo: https://github.com/fetchrobotics/fetch_gazebo/tree/gazebo9/fetch_gazebo_demo/scripts

Thx, Can you tell me the detail information about how to use arm_with_torso_controller/follow_joint_trajectory controller ?
