### ISSUE TITLE
gazebo9 branch

### ISSUE THREAD

**Issue by mikeferguson** [fetchrobotics/fetch_gazebo#21]
Melodic uses gazebo9 -- in the process of updating Navigation stack for Melodic, I had several patches for Gazebo API breaks.

If someone would kindly open a gazebo9 branch, I'll open a PR with the changes.

**Comment by mikeferguson** [comment]
For reference, stuff is here https://github.com/mikeferguson/fetch_gazebo/tree/gazebo9

**Comment by lucbettaieb** [comment]
@rctoris would you make a gazebo9 branch?  I don't have access.

**Comment by rctoris** [comment]
All set.

**Comment by YantianZha** [comment]
Hello all,

Has any of you tried to use the Gazebo 9 with Kinetic? I got the following error:

Errors     << fetch_gazebo:make /home/yz/research/fetch_ws/logs/fetch_gazebo/build.make.009.log
/home/yz/research/fetch_ws/src/fetch_gazebo/fetch_gazebo/src/plugin.cpp: In member function ‘virtual void gazebo::FetchGazeboPlugin::Init()’:
/home/yz/research/fetch_ws/src/fetch_gazebo/fetch_gazebo/src/plugin.cpp:110:71: error: conversion from ‘urdf::JointConstSharedPtr {aka boost::shared_ptr<const urdf::Joint>}’ to non-scalar type ‘std::shared_ptr<const urdf::Joint>’ requested
     std::shared_ptr<const urdf::Joint> urdf_joint = urdfmodel.getJoint((*it)->GetName());
                                                                       ^
make[2]: *** [CMakeFiles/fetch_gazebo_plugin.dir/src/plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/fetch_gazebo_plugin.dir/all] Error 2
make: *** [all] Error 2

Thanks!

**Comment by mikeferguson** [comment]
I think you'll have to make a custom branch if you want to run non-standard Gazebo on Kinetic -- URDF is different between Kinetic/Melodic (switched to std::shared_ptr in Melodic).

**Comment by YantianZha** [comment]
Okay, thanks! I will see if there is a way to fix it. 

BTW: If I keep using Gazebo 7, I would also need to fix a bug of Gazebo about collision checking, to make actors work.
