### ISSUE TITLE
Bug: Simulation fetchit_challenge looks different in RDS & Gazebo

### ISSUE THREAD

**Issue by ben-fido** [fetchrobotics/fetch_gazebo#34]
**Cloud simulator:** RDS (ROS Development Studio), Ubuntu 18.04, ROS Melodic
**Local computer:** Ubuntu 18.04, ROS Melodic, Gazebo 9, NVidia GPU

Has anyone compared the FetchIt Challenge simulator running on RDS with installing on local computer?

**Bug description:**
I find there are various differences, like objects that are not spawned or maybe they are just hidden.
 - The two bolts are blue on RDS but orange on local computer.
 - The two gears. On RDS there is a red and a green gear. My local computer is missing the large green gear.
 - The 3 tables are transparent on local computer.
 - The Schunk machine has different appearance on local computer, like half of it is white instead of grey.
 - The lights are rendered differently. RDS looks more like Gazebo2. Running Gazebo9 on local computer, objects are either too bright or too dark.
 - Non-essential objects like some barrels and a box are missing on local computer.

Here are some screenshots:

![](https://i.postimg.cc/y6Gzy3hj/compare-rds-local-1.png)

![](https://i.postimg.cc/bwB6K1JV/compare-rds-local-2.png)

![](https://i.postimg.cc/DyC5X1qf/compare-rds-local-3.png)

![](https://i.postimg.cc/hPG1chNk/compare-rds-local-4.png)

![](https://i.postimg.cc/65SnKcrZ/compare-rds-local-5.png)

**Comment by moriarty** [comment]
The local version is probably slightly more up to date, because the screws in the bin, shouldn't be the same colour as the bin.

Although the local version lighting looks too bright.

@RDaneelOlivav: I've just invited you to be read-access collaborator on this repository so that I can use the 'assign issue' button.

The floating shelves on invisible tables was also something I witnessed when I tested the PR #32, but we wanted to merge to at least gets something and then continue working on it, it was discussed in that issue and I thought we'd resolved most of the issues.

I suspect, it's a texture and model which is missing form the Catkin Package install, and that the ROS DS server has the textures and models install, or is using the devel space.

**Comment by RDaneelOlivav** [comment]
@moriarty , Just seen this, in my next pull request the floating tables should be resolved ;). How can I see the issues assigned to me ?

**Comment by RDaneelOlivav** [comment]
@ben-fido Also I've created a version with lower lights to accomodate to different needs. The Gazebo simulator renders slightly different the lights in the client, so you will see it different from the Cloud Version. 
But the rendering of the cameras and all the sensors is EXACTLY the same. So please check the cameras also for the one that suits best your needs. I'll post all these changes ASAP.

**Comment by moriarty** [comment]
@ben-fido yes, we're working with @RDaneelOlivav to iterate over the environment and sync everything... We're also building up the physical arena on site which now that it's almost build @velveteenrobot will share all the new measurements and we'll need another iteration of the environment.

Yesterday we did some testing with the real robot, and the real parts, and real Schunk machine and @ajzeller will give one of the gears a longer shaft to increase the tolerance when inserting it into the machine.

We may also update the handle of the machine, the robot is able to grasp the handle and open the door, but the robot needs to do a top down grasp on the current handle, and that essentially wastes some degrees of freedom. I'm looking at changing the handle to make the a horizontal grasp possible and linear motion easier. We'll discuss this with @mmwise and @rctoris.

**Comment by ejichen** [comment]
Also, there is an invisible gear on the desk.
![Screenshot from 2019-03-15 11-08-51](https://user-images.githubusercontent.com/31775247/54452676-f6604b00-4712-11e9-854b-1fc0a2a57edb.png)

**Comment by ejichen** [comment]
Nevermind. The latest version in git fixed the issue.
![Screenshot from 2019-03-15 11-19-54](https://user-images.githubusercontent.com/31775247/54453336-56a3bc80-4714-11e9-8328-0d621c6a50a8.png)

**Comment by moriarty** [comment]
@velveteenrobot has measured our arena environment in house and after the next update I should re-bloom this package.

**Comment by moriarty** [comment]
@ben-fido I'll close this out for now, we've split this up into multiple new tickets:

#47 Additional Kits
#61 Update SCHUNK Machine
#73 Update tables and walls
#74 Update colours of parts

In all cases, the simulation as it is, although different in ROSDS & Gazebo, is already near enough to test components of the challenge code and shouldn't be a blocking issue.

As pointed out by @RDaneelOlivav the how Gazebo renders the scene and lighting may _appear_ different in the view but how that translates into sensor data will not be different. In my experience Gazebo looks differently from machine to machine with the exact same version just based on the GPU in the machine, but the sensor data as seen by the Robot will look the same.
