### ISSUE TITLE
Construct sim with fetch throws an exception

### ISSUE THREAD

**Issue by narora1** [fetchrobotics/fetch_gazebo#40]
I tried getting fetch working on 18.04, melodic and with gazebo 9 but got this exception.

![exception](https://user-images.githubusercontent.com/10620768/54483224-1aa05280-480d-11e9-8ec6-da8052e968c3.png)

Also is there a way I can make edits to the fetch robot model ?

**Comment by RDaneelOlivav** [comment]
I'll check this today for sure, keep you posted.

**Comment by RDaneelOlivav** [comment]
Ok, I'm sharing with you a ROSJECT that I have launched and works:
LINK--> Just click it and you will have it on your space: http://www.rosject.io/l/8361c2a/

![Screenshot from 2019-03-18 21-03-49](https://user-images.githubusercontent.com/4933774/54560061-c4c0db80-49c1-11e9-9dff-4886e97973e2.png)

You just have to launch the main_simple.launch from the package fetchit_challenge from the simulations panel ( select launch file ) and you should get the simulation running.

Any issue please report it so we can resolve it ASAP ;).

**Comment by narora1** [comment]
<img width="1433" alt="Screen Shot 2019-03-19 at 12 24 55 AM" src="https://user-images.githubusercontent.com/10620768/54588696-e9787b80-49e0-11e9-9ee6-6b440494aa9c.png">
It didn't work it timed out waiting for simulation.

**Comment by RDaneelOlivav** [comment]
Ok let me have a look at that in depth because as far as I've tested it worked, save included.

**Comment by RDaneelOlivav** [comment]
Ok we have been debugging and as far as we see to debug the issue we should have access to your system when running. Can you contact me when you make a test so that we can debug this issue? Because we can't reproduce the issue here for some reason. 
@narora1 
duckfrost@gmail.com is my gmail account. Send me an email or a hangouts message and we will be there. We will solve the issue but having your system running and seeing what happens will help a lot for sure.

**Comment by RDaneelOlivav** [comment]
What OS and browser are you using? @narora1

**Comment by narora1** [comment]
Initially it was Firefox and Ubuntu 14.04. The one with the timeout was MacOs on Safari

**Comment by narora1** [comment]
![stuck_loading](https://user-images.githubusercontent.com/10620768/54720104-d0c0b080-4b1b-11e9-8de1-caf6cc208352.png)


It has been 20minutes and it is stuck loading. This is similar to what happened before until it timed out. This time I was using Firefox and ubuntu 14.04. Is there a preferred browser that I should test this on?

**Comment by RDaneelOlivav** [comment]
Hi!
We fixed some issues that we detected due to this, could you retry again, please.
You shouldn't have this error anymore.

Please repost if you have any issue and if not post an image of the ROJect running to see that everything is running ;).

**Comment by narora1** [comment]
![works](https://user-images.githubusercontent.com/10620768/55185277-354dc200-5151-11e9-9fa1-8aac24db5920.png)


works now!!

**Comment by RDaneelOlivav** [comment]
Great to hear it! Remember to pull the fetch_gazebo git once in a while if you want to stay up to date with the improvements and the latest version of the simulation ;)
