### ISSUE TITLE
Update 3D Parts

### ISSUE THREAD

**Issue by moriarty** [fetchrobotics/fetch_gazebo#50]
The 3D parts were originally sized before we were able to turn on the Schunk Machine.

It turned out, that the chuck was not able to close as much as we expected. We've made the shaft of the large gear larger to fit into the machine.

https://github.com/fetchrobotics/fetchit/pull/2

@velveteenrobot

**Comment by RDaneelOlivav** [comment]
Ah ok, understood, I'll work then on the #51
