### ISSUE TITLE
[FetchIt!] Update the screw bin in simulation

### ISSUE THREAD

**Issue by umhan35** [fetchrobotics/fetch_gazebo#81]
@moriarty We saw last week the bin containing screws is updated. Could you update the simulation? @RDaneelOlivav Having the CAD file should be good for now, so we can add ourselves.

Sarah gives the Amazon link: https://www.amazon.com/dp/B00K2NZSFM/

![screw station](https://user-images.githubusercontent.com/3271612/56547838-86808400-654c-11e9-9159-df4767ca3296.png)

**Comment by RDaneelOlivav** [comment]
I wasnt aware of that. You mean that the Bin where the screws are placed has been changed from the small ones to this big bucket like box? @moriarty ?
I'll put in the issues line to change it ;). But I would appreciate more info about this to make it right.

**Comment by moriarty** [comment]
@RDaneelOlivav yes sorry we didn't update you while you were on holiday, and we were still making up our minds.

@velveteenrobot ordered new bins after the first teams accessed the remote area and requested more clearance for the wrist.

We went online and ordered a few difference options and we have been testing them and have now decided on this version.

This is the bin:

https://www.amazon.com/dp/B00K2NZSFM

**Comment by RDaneelOlivav** [comment]
Great! ;). So both the screws and the upper and lower assembly parts will be in these containers? Any colour in particular? All of them are green?

**Comment by ben-fido** [comment]
The two halves of the gearbox will be placed directly on the table surface. No bin.

The screws will be in this green tub:  
https://www.amazon.com/dp/B00K2NZSFM/

 <img src="https://i.imgur.com/kzhSXiG.jpg" height="250">  <img src="https://i.imgur.com/CQadSLH.png" height="250">



.

The dimensions are (in meters):

|                        |  Width on bottom surface | Width at top | Depth on bottom surface | Depth at top | Height |
| ----------------- | -------------------------------- | ---------------- | ------- | -- | -- |
| Inside the tub | 0.450  | 0.470  | 0.335 | 0.350 | 0.125  |
| Outside          |  0.455 |  0.475 | 0.340  | 0.355 |  0.130  |

.

Those dimensions don't include the curved lip around the edges or the handles.

The lip sticks-out 0.020m (all the way around) and is 0.010m high.

The handles are 0.100m along the depth axis, they stick-out 0.040m along the width axis, and are 0.025m high.

.

Is someone going to make a 3D model?

.

**Comment by RDaneelOlivav** [comment]
Thats one of my tasks this week if all goes well ;)

**Comment by moriarty** [comment]
Info from the bottom of the bin:

> CARLISLE
> OKC, OK
www.carlislefsp.com
> N44010

https://www.carlislefsp.com/warewashing/tote-box/N4401009

**Comment by moriarty** [comment]
Can we close this one too?

**Comment by umhan35** [comment]
Can we add the green bin to Gazebo?
