### ISSUE TITLE
[FetchIt!] [BUG] Gazebo world missing romanoff utility caddy

### ISSUE THREAD

**Issue by ben-fido** [fetchrobotics/fetch_gazebo#83]
**Description:**
The kits (Romanoff utility caddy) are missing from some of the Gazebo worlds in the `fetchit_challenge` package.  I think the model URL is wrong and it's trying to download from the internet.

**Steps to reproduce:**
Launch any one of these 4 launch files. They all have the same problem:  
```
roslaunch fetchit_challenge fetchit_challenge_arena_montreal2019_highlights.launch
roslaunch fetchit_challenge fetchit_challenge_arena_montreal2019.launch
roslaunch fetchit_challenge main_arena_montreal2019_highlights.launch
roslaunch fetchit_challenge main_arena_montreal2019.launch
```
In the terminal you see this error message:   
```
[Err] [ModelDatabase.cc:414] Unable to download model[model://romanoff_small_utility_caddy]
```

It is not a bug on my computer because when I use other launch files like `fetchit_challenge_test` the model loads correctly.

.

Here is the full output:   
```
[ INFO] [1556064604.854347292]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1556064604.855203264]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.6
[ INFO] [1556064604.898350072]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1556064604.899131424]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.0.6
[Wrn] [ModelDatabase.cc:340] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Err] [Node.cc:105] No namespace found
[Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[Err] [ModelDatabase.cc:414] Unable to download model[model://romanoff_small_utility_caddy]
[Err] [SystemPaths.cc:412] File or path does not exist[""]
Error Code: 11 Msg: Unable to find uri[model://romanoff_small_utility_caddy]
[ INFO] [1556064624.105415954, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1556064624.123060014, 0.039000000]: Physics dynamic reconfigure ready.

```

**Screenshot:**
Here is a screenshot from "main arena montreal 2019", on the left you can see empty table.

![](https://i.imgur.com/Y5GYII7.png)

**catkin workspace:**
 - fetch_gazebo version: Current master branch
 - Ubuntu version: 18.04
 - ROS version: Melodic

.

**Comment by RDaneelOlivav** [comment]
I'll have a look at this

**Comment by RDaneelOlivav** [comment]
Fixed in: https://github.com/fetchrobotics/fetch_gazebo/pull/85
As soon as it's merged into the main repo gazebo9 branch you should be able to see the cart in all the worlds. I've also updated the assembly elements colors so that they are the grey ones that will be used in the final competition.

**Comment by RDaneelOlivav** [comment]
Oh I didnt see that you need 3 kits on the table. I'm adding right now three of different colour.
Let me know if its ok

**Comment by RDaneelOlivav** [comment]
Done. Now 3 carts appear green, yellow and red. You can change them in the world for any of the colors you want to test your algorithms are robust.
![Screenshot from 2019-04-24 11-52-21](https://user-images.githubusercontent.com/4933774/56650569-99e43a00-6687-11e9-9537-2a96154a4f51.png)

**Comment by ben-fido** [comment]
Thanks @RDaneelOlivav
