### ISSUE TITLE
[Fetchit!] [BUG] Rotated gears "stand up" over time

### ISSUE THREAD

**Issue by GregoryLeMasurier** [fetchrobotics/fetch_gazebo#90]
@RDaneelOlivav When I rotate or spawn in a gear on its side it will start to stand up as seen in the pictures below.
Being able to rotate a gear in simulation would be really useful for testing because in the competition some of the gears will be in this orientation.

**To Reproduce**
Change the roll, pitch, or yaw of any gear's pose to be 1.2.
Change the z of the gear to be above the schunk table (0.83)

Gear after rotation is applied:
![Screenshot from 2019-05-07 11-46-48](https://user-images.githubusercontent.com/15792263/57314258-4dedb800-70bf-11e9-9eb5-b698d6506592.png)

Gear a few seconds after rotation is applied:
![Screenshot from 2019-05-07 11-46-56](https://user-images.githubusercontent.com/15792263/57314269-5219d580-70bf-11e9-810b-7911d4018fb1.png)

**Comment by RDaneelOlivav** [comment]
@moriarty @GregoryLeMasurier I'll solve it tomorrow, is that ok?

**Comment by moriarty** [comment]
Yes Tomorrow should b fine. @GregoryLeMasurier I merged in some changes yesterday which I think should have updated the appearance of the Schunk machine.

**Comment by RDaneelOlivav** [comment]
Ok , I've made a pull request with the changes in the inertias needed to solve this issue: https://github.com/fetchrobotics/fetch_gazebo/pull/92

As soon as this is merged I'll post a ROSJect with the latest changes ;) for you people to use.
